/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as TimelineRouteImport } from './routes/_timeline'
import { Route as TimelineIndexRouteImport } from './routes/_timeline/index'
import { Route as TimelineEntryNewRouteImport } from './routes/_timeline/entry/new'
import { Route as TimelineEntryIdRouteImport } from './routes/_timeline/entry/$id'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/_timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineIndexRoute = TimelineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TimelineRoute,
} as any)
const TimelineEntryNewRoute = TimelineEntryNewRouteImport.update({
  id: '/entry/new',
  path: '/entry/new',
  getParentRoute: () => TimelineRoute,
} as any)
const TimelineEntryIdRoute = TimelineEntryIdRouteImport.update({
  id: '/entry/$id',
  path: '/entry/$id',
  getParentRoute: () => TimelineRoute,
} as any)

export interface FileRoutesByFullPath {
  '/search': typeof SearchRoute
  '/': typeof TimelineIndexRoute
  '/entry/$id': typeof TimelineEntryIdRoute
  '/entry/new': typeof TimelineEntryNewRoute
}
export interface FileRoutesByTo {
  '/search': typeof SearchRoute
  '/': typeof TimelineIndexRoute
  '/entry/$id': typeof TimelineEntryIdRoute
  '/entry/new': typeof TimelineEntryNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_timeline': typeof TimelineRouteWithChildren
  '/search': typeof SearchRoute
  '/_timeline/': typeof TimelineIndexRoute
  '/_timeline/entry/$id': typeof TimelineEntryIdRoute
  '/_timeline/entry/new': typeof TimelineEntryNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/search' | '/' | '/entry/$id' | '/entry/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/search' | '/' | '/entry/$id' | '/entry/new'
  id:
    | '__root__'
    | '/_timeline'
    | '/search'
    | '/_timeline/'
    | '/_timeline/entry/$id'
    | '/_timeline/entry/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  TimelineRoute: typeof TimelineRouteWithChildren
  SearchRoute: typeof SearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_timeline': {
      id: '/_timeline'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_timeline/': {
      id: '/_timeline/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof TimelineIndexRouteImport
      parentRoute: typeof TimelineRoute
    }
    '/_timeline/entry/new': {
      id: '/_timeline/entry/new'
      path: '/entry/new'
      fullPath: '/entry/new'
      preLoaderRoute: typeof TimelineEntryNewRouteImport
      parentRoute: typeof TimelineRoute
    }
    '/_timeline/entry/$id': {
      id: '/_timeline/entry/$id'
      path: '/entry/$id'
      fullPath: '/entry/$id'
      preLoaderRoute: typeof TimelineEntryIdRouteImport
      parentRoute: typeof TimelineRoute
    }
  }
}

interface TimelineRouteChildren {
  TimelineIndexRoute: typeof TimelineIndexRoute
  TimelineEntryIdRoute: typeof TimelineEntryIdRoute
  TimelineEntryNewRoute: typeof TimelineEntryNewRoute
}

const TimelineRouteChildren: TimelineRouteChildren = {
  TimelineIndexRoute: TimelineIndexRoute,
  TimelineEntryIdRoute: TimelineEntryIdRoute,
  TimelineEntryNewRoute: TimelineEntryNewRoute,
}

const TimelineRouteWithChildren = TimelineRoute._addFileChildren(
  TimelineRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  TimelineRoute: TimelineRouteWithChildren,
  SearchRoute: SearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
